belt deploy frontend dev

# 📦 Installing dependencies...
# 🏗️  Building frontend...
# ☁️  Deploying to S3...
# 🔄 Invalidating CloudFront cache...
#
# ✅ Frontend deployed to dev!
#    https://d2tzs58mzfvmlv.cloudfront.net
